# Select the image from which to build the new one
FROM microsoft/iis

# Image label
LABEL Description="stupid website"
LABEL Maintainer="antomate @ GitHub"

# Create website homefolder and configure new IIS website
RUN mkdir C:\stupidewebsite \
  && powershell -NoProfile -Command \
      Import-module IISAdministration; \
      New-IISSite -Name "Site" -PhysicalPath C:\stupidewebsite -BindingInformation "*:8080:"

ADD stupidWebsite/ /stupidewebsite

# Port exposed by the containers (override parent image setting if any)
EXPOSE 8080